contracts=../../solidity_compiler/build/HashManager,../../solidity_compiler/build/TreeHashManager
bootnodes=../../eth_account_creator/build/aefa24a5
validators=../../eth_account_creator/build/aefa24a5,../../eth_account_creator/build/e45e146f,../../eth_account_creator/build/f9667da9