services:
  besu_node:
    build:
      context: .
      dockerfile: Dockerfile
    image: besu_node
    ports:
      - ${BESU_RPC_NETWORK:+${BESU_RPC_NETWORK}:}${BESU_RPC_PORT:+${BESU_RPC_PORT:-8545-8561}:8545}
    volumes:
      - ${BESU_GENESIS_FOLDER}/genesis.json:/sources/network/genesis.json
      - ${BESU_BOOTNODES_FOLDER}/bootnodes.txt:/sources/network/bootnodes.txt
      - ${BESU_KEY_FOLDER}:/sources/account
      - ${BESU_DATA_FOLDER}:/sources/data
    environment:
      BOOTNODES: ${BESU_BOOTNODES}

#     networks:
#       truststorage:
#         ipv4_address: 172.20.0.2

# networks:
#   truststorage:
#     driver: bridge
#     ipam:
#       driver: default
#       config:
#         - subnet: 172.20.0.0/16