x-network-config:

  consensus:
    name: qbft
    parameters:
      blockperiodseconds: 15
      epochlength: 30000
      requesttimeoutseconds: 30

  contracts:
    path: ../contracts
    members:
      - SimpleStorage
      - HashManager
      - TreeHashManager

services:

  node-0:
    image: harbor.rescale-project.eu/rescale-all/besu:2025-05-31
    volumes:
      - ./nodes/node-0:/sources/account
      - ./network:/sources/network
    ports:
      - 127.0.0.1:8545:8545
      - 127.0.0.1:30303:30303
    x-node-config:
      is_bootnode: true
      is_validator: true
      # accounts-allowlist:
      #   - node-0
      # nodes-allowlist:
      #   - node-0
