services:

  localnode-1:
    image: harbor.rescale-project.eu/rescale-all/besu:2025-05-31
    volumes:
      - ./data/account0:/sources/account"
      - ./data/network:/sources/network"
    ports:
      - 127.0.0.1:8545:8545
      - 127.0.0.1:30303:30303