x-network-config:
  account-permissioned: false
  node-permissioned: false
  deployed-contracts:
    - name: SimpleStorage
      balance: ""
      storage: {}
    - name: HashManager
    - name: TreeHashManager

services:
  node-0:
    image: harbor.rescale-project.eu/rescale-all/besu:2025-05-31
    volumes:
      - ./data/node0:/sources/account
      - ./data/network:/sources/network
    ports:
      - 127.0.0.1:8545:8545
      - 127.0.0.1:30303:30303
    x-node-config:
      bootnode: true
      validator: true
